stages:
  - test

lint:
  stage: test
  image: ruby:3.3
  script:
    - bundle install
    - bundle exec rubocop

tests:
  stage: test
  image: ruby:$RUBY_VERSION
  parallel:
    matrix:
      - RUBY_VERSION: ['2.7', '3.0', '3.1', '3.2', '3.3']
  before_script:
    - bin/setup
  script:
    - bundle exec appraisal rspec --format RspecJunitFormatter --out test-results/rspec_$RUBY_VERSION.xml --format documentation
  artifacts:
    reports:
      junit: test-results/rspec*.xml
