inherit_mode:
  merge:
    - Exclude

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - standard

inherit_gem:
  standard: config/base.yml

inherit_from:
  - rubocop/rspec.yml

AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 2.7
  TargetRailsVersion: 5.1

RSpec/FilePath:
  Enabled: false

RSpec/VerifiedDoubles:
  Exclude:
    - spec/**/*_spec.rb

Style/SingleLineMethods:
  Enabled: false

Style/EmptyMethod:
  Enabled: false
