services:
  ruby:
    image: ruby:${RUBY_VERSION:-3.2}
    environment:
      HISTFILE: /app/tmp/.bash_history
      BUNDLE_PATH: /usr/local/bundle
      BUNDLE_CONFIG: /app/.bundle/config
    command: bash
    working_dir: /app
    volumes:
      - .:/app:cached
      - bundler_data:/usr/local/bundle

volumes:
  bundler_data:
