default: &default
  deliver: true
  wait_on_queue_full: true
  max_payload_size: 1000012
  max_wait_timeout: 60000
  ignore_kafka_error: true
  auth:
    kind: plaintext
  kafka:
    servers: "kafka:9092"
    max_retries: 2
    required_acks: -1
    ack_timeout: 1000
    retry_backoff: 1000
    connect_timeout: 2000
    message_timeout: 55000
    kafka_config:
      queue.buffering.max.messages: 1
      queue.buffering.max.ms: 10000

development:
  <<: *default
test:
  <<: *default
  deliver: false
  wait_on_queue_full: false
staging: &staging
  <<: *default
production:
  <<: *staging
